language: java
jdk: openjdk11
services: docker
jobs:
  include:
    - if: type = pull_request
      script:
        - ./mvnw clean package
    - if: type != pull_request and branch IN (staging,master)
      before_script: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      script:
        - ./mvnw clean package
        - docker build -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME
    - if: type != pull_request and branch = master
      script: bash ./scripts/merge-prod-to-staging.sh
    - language: node_js
      node_js:
        - "stable"
      before_install: cd src/main/javascript
      cache:
        directories:
          - src/main/javascript/node_modules
      script:
        - npm test
        - npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app:
          master: chowchow-ui-prod
          staging: chowchow-ui-staging