language: java
jdk: openjdk11
services: docker

before_script:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

jobs:
  include:
    - stage: build and deploy
      github_token: $GITHUB_ACCESS_TOKEN
      verbose: true
      skip_cleanup: true
      script:
        - ./mvnw package
        - docker build -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_PROD
      after_success:
            - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
            - "chmod a+x /tmp/travis-automerge"
            - "BRANCHES_TO_MERGE_REGEX='^' BRANCH_TO_MERGE_INTO=staging GITHUB_REPO=hinosxz/chowchow /tmp/travis-automerge"
#        - bash ./scripts/merge-prod-to-staging.sh
    - stage: build and deploy
      if: branch = staging
      script:
        - ./mvnw package
        - docker build -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_STAGING
