language: java
jdk: openjdk11
services: docker

before_script:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

jobs:
  include:
    - stage: build
      if: type = pull_request
      verbose: true
      script:
        - ./mvnw -X clean package -Dspring.profiles.active=dev
    - stage: build and deploy
      if: branch = master AND type != pull_request
      verbose: true
      script:
        - ./mvnw -X clean package -Dspring.profiles.active=prod
        - docker build -f prod.Dockerfile -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_PROD
      after_success:
        - bash ./scripts/merge-prod-to-staging.sh
    - stage: build and deploy
      if: branch = staging
      script:
        - ./mvnw -X clean package -Dspring.profiles.active=staging
        - docker build -f staging.Dockerfile -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_STAGING