language: java
jdk: openjdk11
services: docker

before_script:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

jobs:
  include:
    - stage: build and deploy
      #if: branch = master
      script:
        - ./mvnw package
        - docker build -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_PROD
