language: java
jdk: openjdk11
services: docker

before_script:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

jobs:
  include:
    - stage: build and deploy
      if: branch = master
      verbose: true
      script:
        - ./mvnw -X clean package -Dspring.profiles.active=prod -Dspring.datasource.url=jdbc:postgresql://$DB_HOST_PROD:5432/$DB_NAME_PROD -Dspring.datasource.username=$DB_USERNAME_PROD -Dspring.datasource.password=$DB_PASSWORD_PROD
        - docker build -f prod.Dockerfile -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_PROD/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_PROD
      after_success:
        - bash ./scripts/merge-prod-to-staging.sh
    - stage: build and deploy
      if: branch = staging
      script:
        - ./mvnw -X clean package -Dspring.profiles.active=staging -Dspring.datasource.url=jdbc:postgresql://$DB_HOST_PROD:5432/$DB_NAME_PROD -Dspring.datasource.username=$DB_USERNAME_PROD -Dspring.datasource.password=$DB_PASSWORD_PROD
        - docker build -f staging.Dockerfile -t chowchow .
        - docker tag chowchow registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
        - docker push registry.heroku.com/$HEROKU_APP_NAME_STAGING/web
        - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app $HEROKU_APP_NAME_STAGING
