version: "3"
services:
  chowchow-db:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chowchow
    restart: unless-stopped

  chowchow-api:
    build: .
    env_file:
      - .env
    environment:
      - DB_URL=chowchow-db
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - chowchow-db
    links:
      - chowchow-db

  chowchow-app:
    build: ./src/main/javascript
    volumes:
      - './src/main/javascript:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    env_file:
      - ./src/main/javascript/.env