DROP TABLE IF EXISTS Shows CASCADE;
CREATE TABLE Shows (
  id SERIAL,
  tmdb_id INTEGER NOT NULL UNIQUE,
  name TEXT NOT NULL,
  year INTEGER NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Users CASCADE;
CREATE TABLE Users (
  id SERIAL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL ,
  type TEXT NOT NULL,
  subscription_type TEXT,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS show_ratings CASCADE;
CREATE TABLE show_ratings (
  user_id SERIAL NOT NULL,
  show_id SERIAL NOT NULL,
  mark INTEGER,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON UPDATE CASCADE,
  FOREIGN KEY(show_id) REFERENCES Shows(id) ON UPDATE CASCADE
);

