DROP TABLE IF EXISTS Users CASCADE;
CREATE TABLE Users (
  id SERIAL,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL ,
  subscription_type INTEGER ,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS likes CASCADE;
CREATE TABLE likes (
  user_id SERIAL NOT NULL,
  show_id SERIAL NOT NULL,
  mark INTEGER,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON UPDATE CASCADE
);